services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
    env_file:
      - ./client/.env
    environment:
      - NODE_ENV=development
      - DOCKER=true

  redis:
    image: redis:7
    ports:
      - "6379:6379"

